### ISSUE TITLE
Update UI to display complex JS objects

### ISSUE THREAD

**Issue by thereisnogabe** [pubky/pkarr#14]
<img width="593" alt="Screenshot 2023-09-14 at 5 25 42 PM" src="https://github.com/Nuhvi/pkarr/assets/7622243/116bed75-20f3-456a-921b-916d9ce85882">

Perhaps a "view detail" tab or similar?

**Comment by Nuhvi** [comment]
In the next update these documents will be saved as TXT records, so it will be shown as a string. But I can privilege TXT records that I know of (like DID, avatar, etc.) like the ENS app https://app.ens.domains/dwr.eth

**Comment by Nuhvi** [comment]
Closing this because, on the one hand, I can't be bothered to make a full-fledged DNS UI editor, and on the other, it can currently read any valid DNS record.

![Screenshot 2023-11-22 at 13 07 22](https://github.com/Nuhvi/pkarr/assets/40009100/94eeaa49-5bf1-4686-972f-f0a36dac0835)
