### ISSUE TITLE
denormalize names

### ISSUE THREAD

**Issue by dvc94ch** [pubky/pkarr#22]
there must be some public api to denormalize the names. when creating a dns packet, pkarr currently makes changes to it and it breaks any user code that does not expect this.

**Comment by Nuhvi** [comment]
Absolutely, can you suggest an API for that? would `signed_packet.packet_with_relative_names()` work for example?

I need the normalized to be the default data for DNS reasons, so maybe I can just make `signed_packet.relative_records()` that returns records directly instead?

**Comment by dvc94ch** [comment]
think `resource_records(&self, name: &str) -> impl Iterator<Item = ResourceRecord>` should work. will open a PR shortly

**Comment by Nuhvi** [comment]
Really appreciate that, are you aware that Pkarr is crate now? I will try to update often as we merge stuff.

**Comment by Nuhvi** [comment]
@dvc94ch should it be `resource_records(&self, name:&str, type: ...)`

**Comment by dvc94ch** [comment]
users can filter for type and convert it. we could add resource_records_txt, resource_records_ip, but not sure if it's worth it

**Comment by Nuhvi** [comment]
Now in Main and v0.1.3
