### ISSUE TITLE
DNS server

### ISSUE THREAD

**Issue by Nuhvi** [pubky/pkarr#39]
I need to build an embedded DNS server that resolves records correctly from Pkarr.

[ ] - resolves CNAME if it doesn't find A records
[ ] - CLI for Pkarr to run the server
[ ] - CLI should hopefully setup the OS DNS servers settings

**Comment by Frando** [comment]
See https://github.com/n0-computer/iroh-dns-server/ for a WIP implementation of a pkarr relay with built-in DNS server. Does not lookup on mainline yet (only serves records published via the HTTPS relay put operation).

**Comment by rklaehn** [comment]
This has now moved into the iroh repo at https://github.com/n0-computer/iroh/tree/main/iroh-dns-server.

And with https://github.com/n0-computer/iroh/pull/2188 it does in fact fall back to the DHT (as an option).

So I think this is exactly what you want.
