### ISSUE TITLE
Add method that returns a stream of signed records

### ISSUE THREAD

**Issue by rklaehn** [pubky/pkarr#40]
Currently there is resolve, resolve_most_recent and resolve_raw.

I realize that you can do whatever you want with resolve_raw, but that is very low level. I got a situation where I published DNS records in an old format, and then got these old DNS records mixed with the new ones. I would like to get a stream of SignedPackets so that I can get the first one that fulfils a certain criterium, like being of the right format or being recent.

**Comment by Nuhvi** [comment]
Closing this since in V2, `resolve()` always return one signed packet (the most recent found so far).
