### ISSUE TITLE
Do not open UDP socket when using PkarrClient only for relay things

### ISSUE THREAD

**Issue by rklaehn** [pubky/pkarr#61]
Currently, as far as I can see PkarrClient will always contain a `Dht` when built with the dht feature flag.

That means that it opens a random UDP port even if you want to use PkarrClient only for e.g. relay_put.

It would be great if you could configure in the builder whether to use the dht at all, independent of the feature flag.

**Comment by Nuhvi** [comment]
>  independent of the feature flag.

Ok, didn't consider that. It will be a bit annoying to keep checking an `Option<Dht>`, but will try it. I am already trying `Arc<Mutex<LruCache>>` so might as well.

**Comment by Nuhvi** [comment]
V2 now has a separate relay client, and all things dht can be disabled by disabling default features and only using `relay` feature

But would love if you take a look and confirm that.
