### ISSUE TITLE
app.pkarr.org doesn't link here

### ISSUE THREAD

**Issue by weex** [pubky/pkarr#92]
There's a link to submit an issue at the bottom of https://app.pkarr.org but it goes to a fork with no issue tracker. Btw, where's the best place to chat with pubky devs?

**Comment by BitcoinErrorLog** [comment]
Everyone is in t.me/pubkychat

**Comment by Nuhvi** [comment]
Thanks @weex, the app is hosted somewhere else, maybe we can move it here at some point.
