### ISSUE TITLE
Is V3 the dev branch?

### ISSUE THREAD

**Issue by weex** [pubky/pkarr#93]
V3 seems to be most advanced but is there a plan to merge that and when. Related question: what code is used in all of the demos.

**Comment by Nuhvi** [comment]
This is the source code of the demo app https://github.com/Nuhvi/pkarr-demo-app

And it uses this old implementation https://www.npmjs.com/package/pkarr

V3 is the most advanced, but it won't introduce any breaking changes at protocol level, you are safe to use the current branch in the meantime.

**Comment by weex** [comment]
Oh you have a Javascript implementation! That might be more palatable to some devs but you say it's old. Is it ok to add to the awesome-pubky thing for those who prefer JS?
